Traceback (most recent call last):
  File "C:/Users/Nathan/Documents/GitHub/automatingPython/chapter10-debugging/tracebackLogging.py", line 6, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
